name: docker build # this doesn't show up in ui

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      artifact-name:
        description: artifact name to download
        type: string
        default: build
    secrets:
      conn_str:
        required: true

jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
        
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
    
    - run: ls -a
      name: ls
      
    - name: deploy
      run: | 
        echo "deploy"
        echo "${{ secrets.CONN_STR }}" # show that secrets work
      
      
