name: docker build # this doesn't show up in ui

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      image-repository:
        description: where to publish/tag image
        type: string
        default: "ghcr.io"
      image-name:
        description: image name
        type: string
        default: "${{ github.repository }}"
      image-tag:
        description: image tag
        type: string
        default: "${{ github.run_number }}"
      dockerfile-path:
        description: image tag
        type: string
        default: "Dockerfile"

jobs:
  docker-build:
    name: docker-build  
    runs-on: ${{ inputs.runs-on }}
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file ${{ inputs.dockerfile-path }} --tag ${{ inputs.image-repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.image-repository }}
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
        
    - name: Push the docker Image
      run: |
        docker push ${{ inputs.image-repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
        docker tag ${{ inputs.image-repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.image-repository }}/${{ inputs.image-name }}:latest
        docker push ${{ inputs.image-repository }}/${{ inputs.image-name }}:latest
      
  docker-deploy-dev:
    name: docker-deploy-dev  
    runs-on: ${{ inputs.runs-on }}
    needs: [docker-build]
    
    steps:
    - run: echo "deploy"
    
  docker-deploy-qa:
    name: docker-deploy-qa  
    runs-on: ${{ inputs.runs-on }}
    needs: [docker-deploy-dev]
    
    steps:
    - run: echo "deploy"   
    
    
