name: docker build # this doesn't show up in ui

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      image-repository:
        description: where to publish/tag image
        type: string
        default: "ghcr.io"
      image-name:
        description: image name
        type: string
        default: "${{ github.repository }}"
      image-tag:
        description: image tag
        type: string
        default: "${{ github.run_number }}"
      dockerfile-path:
        description: image tag
        type: string
        default: "Dockerfile"
# optional with secrets: inherit
#    secrets:
#      registry_password:
#        required: false

jobs:
  docker-build:
    name: docker-build  
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file ${{ inputs.dockerfile-path }} --tag ${{ inputs.image-repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}

    - name: test secret
      run: echo "${{ secrets.registry_password }}" # this will show up as ***

    # use cli instead of action to show secrets in reusable workflows
    # - name: login to cr
    #   run: echo ${{ secrets.registry_password }} | docker login --username foo --password-stdin

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.image-repository }}
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    - name: Push the docker Image
      if: github.actor != 'dependabot[bot]'
      run: |
        docker push ${{ inputs.image-repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
        docker tag ${{ inputs.image-repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.image-repository }}/${{ inputs.image-name }}:latest
        docker push ${{ inputs.image-repository }}/${{ inputs.image-name }}:latest
