name: deploy # this doesn't show up in ui

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
      artifact-name:
        description: artifact name to download
        type: string
        default: build
      environment:
        description: environment in github to target
        type: string
        default: dev
    # using secrets inherit instead
    # secrets:
    #   conn_str:
    #     required: true

jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment }}.mycompany.com
        
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.artifact-name }}
    
    - run: ls -a
      name: ls
      
    - name: deploy
      run: | 
        echo "deploy"
        echo "${{ secrets.CONN_STR }}" # show that secrets works with inherit
      
      
