name: security-checks # this doesn't show up in ui

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest

jobs:
  security-checks:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - run: exit 1
    
